# Top-level configuration
name = "mainWeb2"
main = "src/index.js"
compatibility_date = "2025-02-04"

workers_dev = false
route = { pattern = "https://mainweb2.pages.dev/*", zone_name = "example.org" }

kv_namespaces = [
  { binding = "<main2>", id = "<Workers Builds - 2025-02-04 15:35 >" }
]

