# Top-level configuration
name = "workers-playground-dry-firefly-48a9" 
main = "/index.js"  
compatibility_date = "2025-02-04" 

workers_dev = false  
route = "appleweb.ws384913.workers.dev/*" 

kv_namespaces = [
  { binding = "appleweb", id = "194d1b66fe8-17ab3" }
]